### ISSUE TITLE
Empty string parameters are not passed correctly to choco.exe

### ISSUE THREAD

**Issue by jberezanski** [ethanbergstrom/Foil#3]
When a user provides an empty string as the value of a parameter, such as `--parameters` or `--install-arguments` (which is perfectly legal by choco.exe rules), the empty string is not quoted in the command line passed to choco.exe, so it effectively "disappears", breaking the command line (because the next nonblank token will be interpreted as the value of that parameter and all following parameters will be parsed incorrectly).

Example:

`Install-ChocoPackage -Name cpu-z -Parameters ''`

This should be a valid invocation and would work correctly from cmd.exe (`choco install cpu-z --parameters ""`). However, with Foil, the command line passed to choco.exe will be either
`choco install cpu-z --parameters`
or
`choco install --parameters cpu-z`
(the ordering is not deterministic, because the parameters do not have OriginalPosition defined in Foil and are put in a hashtable, so there are no guarantees and the ordering may change between, for example, .NET versions, including monthly patches)

Both possible command lines sent by Foil are obviously broken.

The root problem seems to be in Crescendo (I've submitted https://github.com/PowerShell/Crescendo/issues/100) and is a consequence of unfortunate PowerShell behavior with regard to passing parameters to native executables, which Crescendo does not take into account.

Considering that the upstream issue may take time to fix (it may be seen as controversial/by design), perhaps it would be best to make Foil immune to it. Given that choco supports also the "equals" syntax (`--package-parameters="foo bar"`), changing the parameter definitions in Foil to use that syntax might fix the problem without depending on Crescendo changes.

**Comment by ethanbergstrom** [comment]
Good catch - all the other optional string-type command parameters use the 'equals' syntax, but `--parameters` and `--install-arguments` aren't. Should be an easy-enough fix.
